version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: bookswap
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}      
    ports:
      - 5434:5432
